/* AUTH */
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const CLEAR_USER_STATE = "CLEAR_USER_STATE";
export const CHECK_CLAIMS = "CHECK_CLAIMS";
export const CHECK_CLAIMS_SUCCESS = "CHECK_CLAIMS_SUCCESS";
export const CHECK_CLAIMS_ERROR = "CHECK_CLAIMS_ERROR";
export const USEREDIT_SUCCESS = "USEREDIT_SUCCESS";
export const USEREDIT_ERROR = "USEREDIT_ERROR";
export const USER_GRANT_ADMIN_SUCCESS = "USER_GRANT_ADMIN_SUCCESS";
export const USER_GRANT_ADMIN_ERROR = "USER_GRANT_ADMIN_ERROR";