/* AUTH */
export const CLEAR_USER_STATE = 'CLEAR_USER_STATE'
export const CHECK_CLAIMS = 'CHECK_CLAIMS'
export const CHECK_CLAIMS_SUCCESS = 'CHECK_CLAIMS_SUCCESS'
export const CHECK_CLAIMS_ERROR = 'CHECK_CLAIMS_ERROR'